name: web_rtc
description: "A new Flutter project."

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  get: any

  flutter_webrtc: ^0.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
